[package]
name = "x3x"
version = "0.1.0"
edition = "2024"
rust-version = "1.97.1"
publish = false

[dependencies]
aegis = { version = "0.9.15", default-features = false, features = ["std", "pure-rust"] }
aes-gcm-siv = { version = "0.11.1", features = ["std"] }
anyhow = "1.0.98"
argon2 = "0.5.3"
ascon-aead = "0.6.0"
chacha20poly1305 = { version = "0.10.1", features = ["std"] }
cipher = "0.5.0"
getrandom = "0.3.3"
hkdf = "0.12.4"
hmac = "0.12.1"
rabbit = { version = "0.5.0", features = ["zeroize"] }
rpassword = "7.4.0"
serpent = { version = "0.6.0", features = ["zeroize"] }
sha2 = "0.10.9"
sha3 = "0.10.8"
tempfile = "3.20.0"
threefish = { version = "0.6.0", features = ["zeroize"] }
zeroize = { version = "1.8.1", features = ["derive"] }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "warn"
pedantic = "warn"
